server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "0811"


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.xxx.springcloud.entities    # 所有Entity别名类所在包